# Generated by Django 5.2.7 on 2026-02-05 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='posted_by',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_collection', models.TextField()),
                ('exported_file', models.FileField(upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.TextField(default='Pending')),
                ('tuition_fee', models.TextField()),
                ('miscellaneous_fee', models.TextField()),
                ('penalties', models.TextField()),
                ('discounts', models.TextField()),
                ('total_amount', models.TextField()),
                ('date_billed', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
