# Generated by Django 5.2.7 on 2026-04-30 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mailsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='discounts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='miscellaneous_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='penalties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='tuition_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='exported_file',
            field=models.FileField(upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx'])]),
        ),
    ]
