# Generated by Django 5.2.7 on 2026-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_billing_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.TextField(default='Accepted'),
        ),
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.TextField(default='Accepted'),
        ),
    ]
