# Generated by Django 5.2.7 on 2026-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_billing_status_students_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.TextField(default='Pending'),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
