# Generated by Django 5.2.7 on 2026-05-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_billing_status_alter_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
