# Generated by Django 5.2.7 on 2026-05-04 01:20

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_billing_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=now
            ),
            preserve_default=False,
        ),
    ]