# Generated by Django 5.2.7 on 2026-05-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
