# Generated by Django 5.2.7 on 2026-05-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_phonenumber_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
