# Generated by Django 5.2.7 on 2026-05-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
