# Generated by Django 5.2.7 on 2026-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_treasurers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasurers',
            name='user',
        ),
        migrations.AddField(
            model_name='treasurers',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treasurers',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
