# Generated by Django 5.2.7 on 2026-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_treasurers_user_treasurers_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurers',
            name='role',
            field=models.CharField(default='pta_treasurer', max_length=50),
        ),
    ]
